name             'pxe'
maintainer       'UAF-GINA'
maintainer_email 'support+chef@gina.alaska.edu'
license          'Apache 2.0'
description      'Installs/Configures pxe'
long_description 'Installs/Configures pxe'
version          '0.1.0'

depends 'apache2'
depends 'tftp'
